{% set name = "cuda-cuobjdump" %}
{% set version = "13.3.73" %}
{% set cuda_version = "13.3" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "windows-x86_64" %}  # [win]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_cuobjdump/{{ platform }}/cuda_cuobjdump-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: 2f3cd496b9183ca2de9e17dbcd7f992eac3cd4475052b151605d9e8445736b94  # [linux64]
  sha256: dfc2b954b540df857a586353d52744f89568e8ca366ef5f2f8890f83da365813  # [aarch64]
  sha256: 02712a1fad9be784aa5b6e930ee22381678f1f1b96e83302bd171489b7dfbb38  # [win]

build:
  number: 0
  binary_relocation: false
  skip: true  # [osx or ppc64le]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - cf-nvidia-tools 1  # [linux]
  host:
    - cuda-version {{ cuda_version }}
  run:
    - {{ pin_compatible("cuda-version", max_pin="x.x") }}
    - cuda-nvdisasm

test:
  requires:
    - patchelf  # [linux]
  files:
    - test-rpath.sh
  commands:
    - test -f $PREFIX/bin/cuobjdump                     # [linux]
    - bash test-rpath.sh                                # [linux]
    - if not exist %LIBRARY_BIN%\\cuobjdump.exe exit 1  # [win]

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Extracts information from CUDA binary files
  description: |
    Extracts information from CUDA binary files and presents them in human
    readable format.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
